model {
  file: "model.sdf"
}
name: "Olive_Kids_Butterfly_Garden_Munch_n_Lunch_Bag"
description: "Olive Kids Butterfly Garden Munch \'n Lunch Bag"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Wildkin"
}
annotations {
  key: "gtin"
  value: "097277551137"
}
annotations {
  key: "mpn"
  value: "55113"
}
annotations {
  key: "sku"
  value: "55113"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Bag"
}
